version: "3.3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: src_kafka_1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#  app:
#    container_name: modular-bank-api
#    restart: always
#    #build: .
#    image: aliguliyev75/modularbank_app
#    ports:
#      - "8080:8080"
#    links:
#      - modular-postgres-db
#      - modular-rabbit-mq
#  modular-postgres-db:
#    environment:
#      POSTGRES_DB: modular
#      POSTGRES_USER: modular
#      POSTGRES_PASSWORD: modular
#    container_name: modular-postgres-db
#    image: postgres
#    ports:
#      - "5432:5432"
#
#  modular-rabbit-mq:
#    container_name: modular-rabbit-mq
#    image: rabbitmq:management
#    ports:
#      - "5672:5672"
#      - "15672:15672"